spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/bancodasinara?createDatabaseIfNotExist=true
    username: root
    password: 39041692
  jackson:
    default-property-inclusion: non_null


spring.mvc.pathmatch.matching-strategy: ant_path_matcher
